[package]
name = "iota-crypto"
version = "0.1.0"
license = "MIT"
authors = ["Gustav Behm <gustav.behm@iota.org>"]
edition = "2018"

[lib]
name = "crypto"

[features]
default = []
xchacha20poly1305 = [ "chacha20poly1305" ]
ed25519 = [ "ed25519-zebra" ]
random = ["rand"]

[dependencies]
chacha20poly1305 = { version = "0.6.0", optional = true }
rand = { version = "0.7", optional = true }

[dependencies.ed25519-zebra]
version = "2.2.0"
optional = true
default-features = false

[dev-dependencies]
hex = "0.4.2"
