[package]
name = "iota-crypto"
version = "0.1.0"
license = "MIT"
authors = ["Gustav Behm <gustav.behm@iota.org>"]
edition = "2018"

[lib]
name = "crypto"

[features]
default = []
#xchacha20poly1305 = [ "chacha20poly1305" ]

[dependencies]
chacha20poly1305 = { version = "0.6.0" }#, optional = true }

bee-common-derive = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
ed25519-dalek = { version = "1.0.0-pre.4", features = ["serde"] }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
signature = "1.2"
slip10 = "0.4"
zeroize = "1.1.0"
