[package]
name = "iota-crypto"
version = "0.1.0"
license = "MIT"
authors = ["Gustav Behm <gustav.behm@iota.org>"]
edition = "2018"

[lib]
name = "crypto"

[features]
default = []
xchacha20poly1305 = [ "chacha20poly1305" ]
ed25519 = ["bee-common-derive", "ed25519-dalek", "rand", "signature", "slip10", "zeroize"]
random = ["rand"]

[dependencies]
# xchacha20poly1305
chacha20poly1305 = { version = "0.6.0", optional = true }
# ed25519
bee-common-derive = { git = "https://github.com/iotaledger/bee.git", branch = "dev", optional = true }
ed25519-dalek = { version = "1.0.0-pre.4", optional = true }
signature = { version = "1.2", optional = true }
slip10 = { version = "0.4", optional = true }
zeroize = { version = "1.1.0", optional = true }
# random
rand = { version = "0.7", optional = true }
